package ru.souz.agent.runtime

import java.util.UUID
import ru.souz.agent.state.AgentContext
import ru.souz.llms.LLMMessageRole
import ru.souz.llms.LLMRequest
import ru.souz.llms.LLMResponse
import ru.souz.llms.ToolInvocationMeta

/** Metadata keys attached to every semantic tool invocation. */
object AgentToolInvocationAttributes {
    const val INVOCATION_ID = "toolInvocationId"
    const val TOOL_NAME = "toolName"
    const val EXECUTION_ID = "executionId"
    const val PROVIDER_TOOL_CALL_ID = "toolCallId"
    const val RESUME_PERMISSION_ID = "resumePermissionId"
}

/**
 * One materialized call in an ordered LLM tool-call batch.
 *
 * [invocationId] is generated by the agent and is independent of the provider's optional
 * [providerToolCallId]. Persisting this value lets a resumed execution retain the same identity.
 */
data class AgentToolInvocation(
    val invocationId: UUID,
    val batchIndex: Int,
    val functionCall: LLMResponse.FunctionCall,
    val providerToolCallId: String? = null,
) {
    init {
        require(batchIndex >= 0) { "AgentToolInvocation.batchIndex must not be negative." }
        require(functionCall.name.isNotBlank()) { "AgentToolInvocation tool name must not be blank." }
    }

    fun invocationMeta(
        base: ToolInvocationMeta,
        resumePermissionId: String? = null,
    ): ToolInvocationMeta {
        val executionId = base.requestId
            ?: base.attributes[AgentToolInvocationAttributes.EXECUTION_ID]
        val invocationKeys = setOf(
            AgentToolInvocationAttributes.INVOCATION_ID,
            AgentToolInvocationAttributes.TOOL_NAME,
            AgentToolInvocationAttributes.EXECUTION_ID,
            AgentToolInvocationAttributes.PROVIDER_TOOL_CALL_ID,
            AgentToolInvocationAttributes.RESUME_PERMISSION_ID,
        )
        val attributes = base.attributes
            .filterKeys { it !in invocationKeys }
            .toMutableMap()
            .apply {
                put(AgentToolInvocationAttributes.INVOCATION_ID, invocationId.toString())
                put(AgentToolInvocationAttributes.TOOL_NAME, functionCall.name)
                executionId?.let { put(AgentToolInvocationAttributes.EXECUTION_ID, it) }
                providerToolCallId?.let { put(AgentToolInvocationAttributes.PROVIDER_TOOL_CALL_ID, it) }
                resumePermissionId?.let { put(AgentToolInvocationAttributes.RESUME_PERMISSION_ID, it) }
            }
        return base.copy(attributes = attributes)
    }
}

/** Complete, ordered set of calls emitted by one assistant response. */
data class AgentToolBatch(
    val batchId: UUID,
    val invocations: List<AgentToolInvocation>,
) {
    init {
        require(invocations.isNotEmpty()) { "AgentToolBatch must contain at least one invocation." }
        require(invocations.map { it.invocationId }.distinct().size == invocations.size) {
            "AgentToolBatch invocation IDs must be unique."
        }
        require(invocations.map { it.batchIndex } == invocations.indices.toList()) {
            "AgentToolBatch indices must be contiguous and ordered."
        }
    }
}

enum class AgentToolBatchCheckpointPhase {
    /** The complete batch was persisted before invoking its first call. */
    PLANNED,

    /** An exact function-result message was added to history and persisted. */
    RESULT_STORED,

    /** A stored checkpoint was claimed for continuation. */
    RESUMING,
}

/**
 * Semantic checkpoint emitted at the only safe boundaries of a tool batch.
 *
 * [nextInvocationIndex] points at the first call whose result is not present in [history].
 */
data class AgentToolBatchCheckpoint(
    val batch: AgentToolBatch,
    val nextInvocationIndex: Int,
    val history: List<LLMRequest.Message>,
    val phase: AgentToolBatchCheckpointPhase,
) {
    init {
        require(nextInvocationIndex in 0..batch.invocations.size) {
            "AgentToolBatchCheckpoint.nextInvocationIndex is outside the batch."
        }
    }
}

/**
 * Execution-scoped durable checkpoint hook.
 *
 * Implementations must not return until the checkpoint is durable. [NONE] keeps desktop and
 * Android behavior unchanged.
 */
fun interface AgentToolBatchCheckpointSink {
    suspend fun save(
        checkpoint: AgentToolBatchCheckpoint,
        context: AgentContext<*>,
    )

    companion object {
        val NONE: AgentToolBatchCheckpointSink = AgentToolBatchCheckpointSink { _, _ -> }
    }
}

/**
 * Input to the dedicated post-checkpoint graph.
 *
 * A denied permission is represented by [pendingResult], which is stored without invoking the
 * current tool. A grant sets [resumePermissionId] and re-enters the exact stored call. Invocations
 * in [startedInvocationIds] do not emit a duplicate `tool.call.started` event when re-entered.
 */
data class AgentToolBatchResume(
    val batch: AgentToolBatch,
    val nextInvocationIndex: Int,
    val pendingResult: LLMRequest.Message? = null,
    val resumePermissionId: String? = null,
    val startedInvocationIds: Set<UUID> = emptySet(),
) {
    init {
        require(nextInvocationIndex in 0..batch.invocations.size) {
            "AgentToolBatchResume.nextInvocationIndex is outside the batch."
        }
        require(pendingResult == null || resumePermissionId == null) {
            "A resumed invocation cannot both execute and use a pending result."
        }
        require(pendingResult == null || nextInvocationIndex < batch.invocations.size) {
            "A pending result requires a current invocation."
        }
        require(pendingResult == null || pendingResult.role == LLMMessageRole.function) {
            "A pending tool result must be a function message."
        }
        require(resumePermissionId == null || resumePermissionId.isNotBlank()) {
            "AgentToolBatchResume.resumePermissionId must not be blank."
        }
        require(startedInvocationIds.all { started -> batch.invocations.any { it.invocationId == started } }) {
            "Started invocation IDs must belong to the resumed batch."
        }
    }

    companion object {
        const val USER_DISAPPROVED_MESSAGE = "User disapproved"

        fun denied(
            batch: AgentToolBatch,
            nextInvocationIndex: Int,
            startedInvocationIds: Set<UUID> = emptySet(),
            message: String = USER_DISAPPROVED_MESSAGE,
        ): AgentToolBatchResume = AgentToolBatchResume(
            batch = batch,
            nextInvocationIndex = nextInvocationIndex,
            pendingResult = LLMRequest.Message(
                role = LLMMessageRole.function,
                content = message,
            ),
            startedInvocationIds = startedInvocationIds,
        )
    }
}

/**
 * Non-cancellation control-flow signal used when an execution has been durably parked.
 *
 * Agent layers propagate this signal without failed-tool events or failure telemetry. Backend
 * permission requesters can subclass it to attach their durable request identity.
 */
open class AgentExecutionPause(
    message: String,
    cause: Throwable? = null,
) : RuntimeException(message, cause)
